# Generated by Django 3.2.3 on 2021-06-02 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Business Name')),
                ('subtitle', models.CharField(max_length=500, verbose_name='Short Description')),
            ],
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=500, verbose_name='Short Description')),
                ('parent_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_business.organization')),
            ],
        ),
        migrations.CreateModel(
            name='AlgoUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Step Title')),
                ('parent_process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_business.process')),
            ],
        ),
    ]
