# Generated by Django 3.2.3 on 2021-06-25 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='title',
        ),
        migrations.AddField(
            model_name='organization',
            name='is_owned_by_me',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
