# Generated by Django 3.2.3 on 2021-06-02 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_business', '0002_organization_parent_organization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='parent_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general_business.organization', verbose_name='Parent Organization'),
        ),
    ]
