# Generated by Django 3.2.3 on 2021-06-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_business', '0002_auto_20210624_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Business Name'),
        ),
    ]
