# Generated by Django 3.2.3 on 2021-06-02 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_business', '0004_venture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Campaign Title')),
                ('subtitle', models.CharField(max_length=300, verbose_name='Short Description')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=300, verbose_name='Short Description')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Service Title')),
                ('is_recurring', models.BooleanField(verbose_name='Is this service recurring?')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='venture',
            name='is_campaign',
        ),
        migrations.RemoveField(
            model_name='venture',
            name='is_product',
        ),
        migrations.RemoveField(
            model_name='venture',
            name='is_service',
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(max_length=500, verbose_name='Short Description')),
                ('parent_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_business.organization')),
            ],
        ),
    ]
