# Generated by Django 3.2.3 on 2021-06-02 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_business', '0005_auto_20210601_2144'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=300, null=True, verbose_name='Product Title'),
        ),
    ]
