# Generated by Django 3.2.3 on 2021-06-02 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_business', '0007_feature_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='parent_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general_business.organization', verbose_name='Parent Organization'),
        ),
        migrations.AddField(
            model_name='project',
            name='subtitle',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='product',
            name='subtitle',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Service Title'),
        ),
    ]
