# Generated by Django 3.2.3 on 2021-06-02 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_business', '0008_auto_20210602_1624'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='parent_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general_business.organization'),
        ),
        migrations.AddField(
            model_name='product',
            name='parent_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general_business.organization'),
        ),
        migrations.AddField(
            model_name='service',
            name='parent_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general_business.organization'),
        ),
        migrations.AddField(
            model_name='venture',
            name='parent_organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general_business.organization'),
        ),
    ]
