# Generated by Django 3.2.3 on 2021-06-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general_business', '0009_auto_20210602_1631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='parent_organization',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='parent_product',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='parent_service',
        ),
        migrations.RemoveField(
            model_name='process',
            name='parent_organization',
        ),
        migrations.RemoveField(
            model_name='product',
            name='parent_organization',
        ),
        migrations.RemoveField(
            model_name='project',
            name='parent_organization',
        ),
        migrations.RemoveField(
            model_name='service',
            name='parent_organization',
        ),
        migrations.DeleteModel(
            name='AlgoUnit',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='Process',
        ),
    ]
