# Generated by Django 3.2.3 on 2021-06-03 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0003_auto_20210603_1328'),
        ('general_business', '0010_auto_20210603_1328'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
