# Generated by Django 3.2.3 on 2021-06-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general_business', '0011_auto_20210603_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='title',
            field=models.CharField(default='fdjksjlkg', max_length=300, verbose_name='Role Title'),
            preserve_default=False,
        ),
    ]
