# Generated by Django 3.2.3 on 2021-06-03 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
