# Generated by Django 3.2.3 on 2021-06-16 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_abstractdescmodel_book_chapter_chapterintroquote_chaptersection_paragraph'),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceObj',
            fields=[
                ('abstractdescmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.abstractdescmodel')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(verbose_name='Is this a recurring payment?')),
                ('recurrence_freq', models.CharField(blank=True, max_length=500, null=True)),
                ('parent_product', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.abstractdescmodel',),
        ),
    ]
