# Generated by Django 3.2.3 on 2021-06-15 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0002_abstractdescmodel_book_chapter_chapterintroquote_chaptersection_paragraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutonomousAnalysis',
            fields=[
                ('abstractdescmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.abstractdescmodel')),
                ('function_class_name', models.CharField(blank=True, max_length=500, null=True, verbose_name='What is the class name of the corresponding view?')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.abstractdescmodel',),
        ),
    ]
