# Generated by Django 3.2.3 on 2021-06-15 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0001_initial'),
        ('modules', '0001_initial'),
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='autonomousanalysis',
            name='metrics',
            field=models.ManyToManyField(blank=True, to='metrics.Metric'),
        ),
        migrations.AddField(
            model_name='autonomousanalysis',
            name='parent_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modules.module'),
        ),
    ]
