# Generated by Django 3.2.3 on 2021-06-03 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_business', '0010_auto_20210603_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_svg', models.ImageField(blank=True, null=True, upload_to='', verbose_name='SVG file of logo')),
                ('mantra', models.CharField(blank=True, max_length=250, null=True, verbose_name='Brand Mantra')),
                ('colors', models.JSONField(blank=True, null=True, verbose_name='Store brand colors in JSON format.')),
                ('logo_mockup', models.ImageField(upload_to='', verbose_name='Enter a logo mockup image')),
                ('topic_keywords', models.CharField(max_length=10000, verbose_name='Enter keywords describing your brand, separated by commas.')),
                ('parent_organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general_business.organization')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_medium', models.CharField(max_length=300, verbose_name='What is the social medium of this social media account?')),
                ('username', models.CharField(max_length=300, verbose_name='What is the username of this social media account?')),
                ('password', models.CharField(max_length=300, verbose_name='What is the password of this social media account?')),
                ('purpose', models.CharField(max_length=500, verbose_name='What is the purpose of this social media account?')),
                ('page_url', models.URLField(verbose_name='Enter social media page URL.')),
                ('parent_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='marketing.brand')),
            ],
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Campaign Title')),
                ('subtitle', models.CharField(max_length=300, verbose_name='Short Description')),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('parent_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general_business.organization')),
            ],
        ),
    ]
