# Generated by Django 3.2.3 on 2021-06-16 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Process Title')),
                ('subtitle', models.CharField(blank=True, max_length=500, verbose_name='Short Description')),
                ('parent_organization', models.ManyToManyField(blank=True, to='general_business.Organization')),
                ('subprocess', models.ManyToManyField(blank=True, related_name='+', to='processes.Process')),
            ],
        ),
    ]
