# Generated by Django 3.2.3 on 2021-06-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='process',
            name='title',
            field=models.CharField(default='jdkflsjfk', max_length=300, verbose_name='Process Title'),
            preserve_default=False,
        ),
    ]
