# Generated by Django 3.2.3 on 2021-06-10 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractbudgetitem',
            name='is_prospective',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractbudgetitem',
            name='live_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abstractbudgetitem',
            name='parent_budget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='budgeting.budget'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_asset',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is this an asset?'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='is_business_expense',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is this a business expense?'),
        ),
    ]
