# Generated by Django 3.2.3 on 2021-06-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0002_auto_20210610_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomeevent',
            name='is_prospective',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is this a future income event?'),
        ),
    ]
