# Generated by Django 3.2.3 on 2021-06-03 21:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('general_business', '0011_auto_20210603_1328'),
        ('budgeting', '0004_incomeevent_incomestream'),
    ]

    operations = [
        migrations.AddField(
            model_name='incomestream',
            name='parent_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general_business.role'),
        ),
        migrations.AddField(
            model_name='incomestream',
            name='title',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Income Source Title'),
        ),
    ]
