# Generated by Django 3.2.3 on 2021-06-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgeting', '0005_auto_20210603_1406'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_essential',
            field=models.BooleanField(blank=True, null=True, verbose_name='Is this expense essential?'),
        ),
        migrations.AlterField(
            model_name='budget',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Budget Title'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Expense Title'),
        ),
    ]
