# Generated by Django 3.2.3 on 2021-06-21 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nav', '0002_alter_dirtreefolder_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dirtreefolder',
            name='path',
        ),
        migrations.AddField(
            model_name='dirtreefolder',
            name='parent_folder',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='nav.dirtreefolder'),
        ),
        migrations.CreateModel(
            name='DirTreeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='default title', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('extension', models.CharField(blank=True, max_length=500, null=True)),
                ('parent_folder', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='nav.dirtreefolder')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
