# Generated by Django 3.2.3 on 2021-06-03 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('general_business', '0010_auto_20210603_1328'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Project Title')),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True, verbose_name='Short Description')),
                ('parent_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general_business.organization', verbose_name='Parent Organization')),
            ],
        ),
    ]
