# Generated by Django 3.2.3 on 2021-06-08 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('general_business', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='default title', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True, verbose_name='Short Description')),
                ('parent_organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='general_business.organization', verbose_name='Parent Organization')),
                ('parent_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product', verbose_name='Parent Product')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='default title', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True, verbose_name='Short Description')),
                ('description', models.CharField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('parent_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.product')),
                ('parent_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.project')),
                ('parent_service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
