# Generated by Django 3.2.3 on 2021-06-24 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='feature_type',
            field=models.CharField(blank=True, choices=[('User-Facing Feature', 'User-Facing Feature'), ('Development Feature', 'Development Feature'), ('UI Design Feature', 'UI Design Feature')], max_length=400, null=True),
        ),
    ]
