# Generated by Django 3.2.3 on 2021-06-25 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_abstractvideomodel_subtitle_transcription'),
        ('project', '0002_feature_feature_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('abstractdescmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.abstractdescmodel')),
                ('parent_feature', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project.feature')),
                ('subtasks', models.ManyToManyField(blank=True, null=True, to='project.Task')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.abstractdescmodel',),
        ),
    ]
