# Generated by Django 3.2.3 on 2021-06-25 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_tech'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='next_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='next_task_relation', to='project.task'),
        ),
        migrations.AddField(
            model_name='task',
            name='previous_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='previous_task_relation', to='project.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='subtasks',
            field=models.ManyToManyField(blank=True, null=True, related_name='subtask_relation', to='project.Task'),
        ),
    ]
