# Generated by Django 3.2.3 on 2021-06-25 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20210624_1854'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tech',
            name='parent_feature',
        ),
        migrations.AddField(
            model_name='tech',
            name='parent_feature',
            field=models.ManyToManyField(blank=True, null=True, to='project.Feature'),
        ),
    ]
