# Generated by Django 3.2.3 on 2021-06-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20210624_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='subfeatures',
            field=models.ManyToManyField(blank=True, null=True, to='project.Feature'),
        ),
    ]
