# Generated by Django 3.2.3 on 2021-06-25 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20210624_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='parent_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='project.project'),
        ),
    ]
