# Generated by Django 3.2.3 on 2021-06-08 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='What is the company name?')),
                ('page_url', models.URLField(blank=True, null=True, verbose_name="Enter a URL to the company's website")),
                ('linked_in_url', models.URLField(blank=True, null=True, verbose_name="Enter a URL to the company's LinkedIn page.")),
                ('company_type', models.CharField(blank=True, max_length=300, null=True, verbose_name='What is the company type (LLC, S-Corp, etc)?')),
                ('company_size', models.CharField(blank=True, max_length=300, null=True, verbose_name='What is the company size (SME, Startup, Corporate Behemoth, etc)?')),
                ('employee_count', models.CharField(blank=True, max_length=300, null=True, verbose_name="What is the company's employee count?")),
            ],
        ),
        migrations.CreateModel(
            name='CareerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='What is the role title?')),
                ('parent_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='career.company')),
            ],
        ),
        migrations.CreateModel(
            name='CareerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=300, null=True, verbose_name="What is your contact's first name?")),
                ('alias', models.CharField(blank=True, max_length=300, null=True, verbose_name='If your contact has one, what is their alias?')),
                ('last_name', models.CharField(blank=True, max_length=300, null=True, verbose_name="What is your contact's last name?")),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, max_length=500, null=True)),
                ('parent_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='career.company')),
            ],
        ),
    ]
