# Generated by Django 3.2.3 on 2021-06-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='What is the company type (LLC, S-Corp, etc)?'),
        ),
    ]
