# Generated by Django 3.2.3 on 2021-06-08 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractAudioModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='default title', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('mp3_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='MP3 file')),
                ('wav_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='WAV file')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AbstractImgModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='default title', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('png_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='PNG file')),
                ('svg_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='SVG file')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TwitterThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='default title', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstagramCarousel',
            fields=[
                ('abstractimgmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.abstractimgmodel')),
                ('count', models.IntegerField(verbose_name='Page Count')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.abstractimgmodel',),
        ),
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='default title', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('img_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Image File')),
                ('content_text', models.CharField(blank=True, max_length=250, null=True)),
                ('date_uploaded', models.DateTimeField(auto_now=True)),
                ('parent_thread', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='content.twitterthread')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='default title', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('content_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='What is the file playing in the background of this story?')),
                ('poll_question', models.CharField(blank=True, max_length=500, null=True)),
                ('social_account', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='marketing.socialmediaaccount')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InstagramCarouselPage',
            fields=[
                ('abstractimgmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.abstractimgmodel')),
                ('parent_carousel', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='content.instagramcarousel')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.abstractimgmodel',),
        ),
    ]
