# Generated by Django 3.2.3 on 2021-06-09 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractDescModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='default title', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='default title', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('abstractdescmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.abstractdescmodel')),
                ('parent_book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.book')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.abstractdescmodel',),
        ),
        migrations.CreateModel(
            name='ChapterSection',
            fields=[
                ('abstractdescmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.abstractdescmodel')),
                ('parent_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.chapter')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.abstractdescmodel',),
        ),
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('abstractdescmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.abstractdescmodel')),
                ('body', models.CharField(blank=True, max_length=1000000, null=True)),
                ('parent_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.chapter')),
                ('parent_chapter_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.chaptersection')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.abstractdescmodel',),
        ),
        migrations.CreateModel(
            name='ChapterIntroQuote',
            fields=[
                ('abstractdescmodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.abstractdescmodel')),
                ('parent_chapter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.chapter')),
            ],
            options={
                'abstract': False,
            },
            bases=('content.abstractdescmodel',),
        ),
    ]
