# Generated by Django 3.2.3 on 2021-06-23 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_abstractdescmodel_book_chapter_chapterintroquote_chaptersection_paragraph'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractVideoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='default title', max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('video_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Video File')),
                ('subtitle_transcription', models.JSONField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('abstractvideomodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='content.abstractvideomodel')),
                ('type', models.CharField(blank=True, choices=[('Tutorial', 'Tutorial'), ('Monologue', 'Monologue'), ('Podcast', 'Podcast'), ('Diagram Explanation', 'Diagram Explanation')], max_length=500, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('content.abstractvideomodel',),
        ),
    ]
