# Generated by Django 3.2.3 on 2021-06-23 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_abstractvideomodel_videocontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstractvideomodel',
            name='subtitle_transcription',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
